# Generated by Django 3.2.2 on 2021-05-12 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LifeProTips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
